services:

  messagerie:
    build: .

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    environment:
      NODE_ENV: production
